export const GET_ARTICLES='GET_ARTICLES';
export const GET_ARTICLES_SUCESS='GET_ARTICLES_SUCESS';
export const GET_ARTICLES_ERROR='GET_ARTICLES_ERROR';
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_COUNTRY= 'SET_COUNTRY';